# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vita/programovani/bp/AutoCropApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vita/programovani/bp/AutoCropApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vita/programovani/bp/AutoCropApp/CMakeFiles /home/vita/programovani/bp/AutoCropApp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vita/programovani/bp/AutoCropApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vlfeats

# Build rule for target.
vlfeats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vlfeats
.PHONY : vlfeats

# fast build rule for target.
vlfeats/fast:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/build
.PHONY : vlfeats/fast

#=============================================================================
# Target rules for targets named autocrop

# Build rule for target.
autocrop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autocrop
.PHONY : autocrop

# fast build rule for target.
autocrop/fast:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/build
.PHONY : autocrop/fast

src/Arguments.o: src/Arguments.cpp.o

.PHONY : src/Arguments.o

# target to build an object file
src/Arguments.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Arguments.cpp.o
.PHONY : src/Arguments.cpp.o

src/Arguments.i: src/Arguments.cpp.i

.PHONY : src/Arguments.i

# target to preprocess a source file
src/Arguments.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Arguments.cpp.i
.PHONY : src/Arguments.cpp.i

src/Arguments.s: src/Arguments.cpp.s

.PHONY : src/Arguments.s

# target to generate assembly for a file
src/Arguments.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Arguments.cpp.s
.PHONY : src/Arguments.cpp.s

src/AutocropFang.o: src/AutocropFang.cpp.o

.PHONY : src/AutocropFang.o

# target to build an object file
src/AutocropFang.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropFang.cpp.o
.PHONY : src/AutocropFang.cpp.o

src/AutocropFang.i: src/AutocropFang.cpp.i

.PHONY : src/AutocropFang.i

# target to preprocess a source file
src/AutocropFang.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropFang.cpp.i
.PHONY : src/AutocropFang.cpp.i

src/AutocropFang.s: src/AutocropFang.cpp.s

.PHONY : src/AutocropFang.s

# target to generate assembly for a file
src/AutocropFang.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropFang.cpp.s
.PHONY : src/AutocropFang.cpp.s

src/AutocropStentiford.o: src/AutocropStentiford.cpp.o

.PHONY : src/AutocropStentiford.o

# target to build an object file
src/AutocropStentiford.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropStentiford.cpp.o
.PHONY : src/AutocropStentiford.cpp.o

src/AutocropStentiford.i: src/AutocropStentiford.cpp.i

.PHONY : src/AutocropStentiford.i

# target to preprocess a source file
src/AutocropStentiford.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropStentiford.cpp.i
.PHONY : src/AutocropStentiford.cpp.i

src/AutocropStentiford.s: src/AutocropStentiford.cpp.s

.PHONY : src/AutocropStentiford.s

# target to generate assembly for a file
src/AutocropStentiford.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropStentiford.cpp.s
.PHONY : src/AutocropStentiford.cpp.s

src/AutocropSuh.o: src/AutocropSuh.cpp.o

.PHONY : src/AutocropSuh.o

# target to build an object file
src/AutocropSuh.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropSuh.cpp.o
.PHONY : src/AutocropSuh.cpp.o

src/AutocropSuh.i: src/AutocropSuh.cpp.i

.PHONY : src/AutocropSuh.i

# target to preprocess a source file
src/AutocropSuh.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropSuh.cpp.i
.PHONY : src/AutocropSuh.cpp.i

src/AutocropSuh.s: src/AutocropSuh.cpp.s

.PHONY : src/AutocropSuh.s

# target to generate assembly for a file
src/AutocropSuh.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/AutocropSuh.cpp.s
.PHONY : src/AutocropSuh.cpp.s

src/CompositionModel.o: src/CompositionModel.cpp.o

.PHONY : src/CompositionModel.o

# target to build an object file
src/CompositionModel.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/CompositionModel.cpp.o
.PHONY : src/CompositionModel.cpp.o

src/CompositionModel.i: src/CompositionModel.cpp.i

.PHONY : src/CompositionModel.i

# target to preprocess a source file
src/CompositionModel.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/CompositionModel.cpp.i
.PHONY : src/CompositionModel.cpp.i

src/CompositionModel.s: src/CompositionModel.cpp.s

.PHONY : src/CompositionModel.s

# target to generate assembly for a file
src/CompositionModel.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/CompositionModel.cpp.s
.PHONY : src/CompositionModel.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/SalMapItti.o: src/SalMapItti.cpp.o

.PHONY : src/SalMapItti.o

# target to build an object file
src/SalMapItti.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapItti.cpp.o
.PHONY : src/SalMapItti.cpp.o

src/SalMapItti.i: src/SalMapItti.cpp.i

.PHONY : src/SalMapItti.i

# target to preprocess a source file
src/SalMapItti.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapItti.cpp.i
.PHONY : src/SalMapItti.cpp.i

src/SalMapItti.s: src/SalMapItti.cpp.s

.PHONY : src/SalMapItti.s

# target to generate assembly for a file
src/SalMapItti.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapItti.cpp.s
.PHONY : src/SalMapItti.cpp.s

src/SalMapMargolin.o: src/SalMapMargolin.cpp.o

.PHONY : src/SalMapMargolin.o

# target to build an object file
src/SalMapMargolin.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapMargolin.cpp.o
.PHONY : src/SalMapMargolin.cpp.o

src/SalMapMargolin.i: src/SalMapMargolin.cpp.i

.PHONY : src/SalMapMargolin.i

# target to preprocess a source file
src/SalMapMargolin.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapMargolin.cpp.i
.PHONY : src/SalMapMargolin.cpp.i

src/SalMapMargolin.s: src/SalMapMargolin.cpp.s

.PHONY : src/SalMapMargolin.s

# target to generate assembly for a file
src/SalMapMargolin.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapMargolin.cpp.s
.PHONY : src/SalMapMargolin.cpp.s

src/SalMapStentiford.o: src/SalMapStentiford.cpp.o

.PHONY : src/SalMapStentiford.o

# target to build an object file
src/SalMapStentiford.cpp.o:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapStentiford.cpp.o
.PHONY : src/SalMapStentiford.cpp.o

src/SalMapStentiford.i: src/SalMapStentiford.cpp.i

.PHONY : src/SalMapStentiford.i

# target to preprocess a source file
src/SalMapStentiford.cpp.i:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapStentiford.cpp.i
.PHONY : src/SalMapStentiford.cpp.i

src/SalMapStentiford.s: src/SalMapStentiford.cpp.s

.PHONY : src/SalMapStentiford.s

# target to generate assembly for a file
src/SalMapStentiford.cpp.s:
	$(MAKE) -f CMakeFiles/autocrop.dir/build.make CMakeFiles/autocrop.dir/src/SalMapStentiford.cpp.s
.PHONY : src/SalMapStentiford.cpp.s

vlfeat/vl/generic.o: vlfeat/vl/generic.c.o

.PHONY : vlfeat/vl/generic.o

# target to build an object file
vlfeat/vl/generic.c.o:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/generic.c.o
.PHONY : vlfeat/vl/generic.c.o

vlfeat/vl/generic.i: vlfeat/vl/generic.c.i

.PHONY : vlfeat/vl/generic.i

# target to preprocess a source file
vlfeat/vl/generic.c.i:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/generic.c.i
.PHONY : vlfeat/vl/generic.c.i

vlfeat/vl/generic.s: vlfeat/vl/generic.c.s

.PHONY : vlfeat/vl/generic.s

# target to generate assembly for a file
vlfeat/vl/generic.c.s:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/generic.c.s
.PHONY : vlfeat/vl/generic.c.s

vlfeat/vl/host.o: vlfeat/vl/host.c.o

.PHONY : vlfeat/vl/host.o

# target to build an object file
vlfeat/vl/host.c.o:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/host.c.o
.PHONY : vlfeat/vl/host.c.o

vlfeat/vl/host.i: vlfeat/vl/host.c.i

.PHONY : vlfeat/vl/host.i

# target to preprocess a source file
vlfeat/vl/host.c.i:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/host.c.i
.PHONY : vlfeat/vl/host.c.i

vlfeat/vl/host.s: vlfeat/vl/host.c.s

.PHONY : vlfeat/vl/host.s

# target to generate assembly for a file
vlfeat/vl/host.c.s:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/host.c.s
.PHONY : vlfeat/vl/host.c.s

vlfeat/vl/random.o: vlfeat/vl/random.c.o

.PHONY : vlfeat/vl/random.o

# target to build an object file
vlfeat/vl/random.c.o:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/random.c.o
.PHONY : vlfeat/vl/random.c.o

vlfeat/vl/random.i: vlfeat/vl/random.c.i

.PHONY : vlfeat/vl/random.i

# target to preprocess a source file
vlfeat/vl/random.c.i:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/random.c.i
.PHONY : vlfeat/vl/random.c.i

vlfeat/vl/random.s: vlfeat/vl/random.c.s

.PHONY : vlfeat/vl/random.s

# target to generate assembly for a file
vlfeat/vl/random.c.s:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/random.c.s
.PHONY : vlfeat/vl/random.c.s

vlfeat/vl/slic.o: vlfeat/vl/slic.c.o

.PHONY : vlfeat/vl/slic.o

# target to build an object file
vlfeat/vl/slic.c.o:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/slic.c.o
.PHONY : vlfeat/vl/slic.c.o

vlfeat/vl/slic.i: vlfeat/vl/slic.c.i

.PHONY : vlfeat/vl/slic.i

# target to preprocess a source file
vlfeat/vl/slic.c.i:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/slic.c.i
.PHONY : vlfeat/vl/slic.c.i

vlfeat/vl/slic.s: vlfeat/vl/slic.c.s

.PHONY : vlfeat/vl/slic.s

# target to generate assembly for a file
vlfeat/vl/slic.c.s:
	$(MAKE) -f CMakeFiles/vlfeats.dir/build.make CMakeFiles/vlfeats.dir/vlfeat/vl/slic.c.s
.PHONY : vlfeat/vl/slic.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vlfeats"
	@echo "... autocrop"
	@echo "... src/Arguments.o"
	@echo "... src/Arguments.i"
	@echo "... src/Arguments.s"
	@echo "... src/AutocropFang.o"
	@echo "... src/AutocropFang.i"
	@echo "... src/AutocropFang.s"
	@echo "... src/AutocropStentiford.o"
	@echo "... src/AutocropStentiford.i"
	@echo "... src/AutocropStentiford.s"
	@echo "... src/AutocropSuh.o"
	@echo "... src/AutocropSuh.i"
	@echo "... src/AutocropSuh.s"
	@echo "... src/CompositionModel.o"
	@echo "... src/CompositionModel.i"
	@echo "... src/CompositionModel.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/SalMapItti.o"
	@echo "... src/SalMapItti.i"
	@echo "... src/SalMapItti.s"
	@echo "... src/SalMapMargolin.o"
	@echo "... src/SalMapMargolin.i"
	@echo "... src/SalMapMargolin.s"
	@echo "... src/SalMapStentiford.o"
	@echo "... src/SalMapStentiford.i"
	@echo "... src/SalMapStentiford.s"
	@echo "... vlfeat/vl/generic.o"
	@echo "... vlfeat/vl/generic.i"
	@echo "... vlfeat/vl/generic.s"
	@echo "... vlfeat/vl/host.o"
	@echo "... vlfeat/vl/host.i"
	@echo "... vlfeat/vl/host.s"
	@echo "... vlfeat/vl/random.o"
	@echo "... vlfeat/vl/random.i"
	@echo "... vlfeat/vl/random.s"
	@echo "... vlfeat/vl/slic.o"
	@echo "... vlfeat/vl/slic.i"
	@echo "... vlfeat/vl/slic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

